version: '3.4'

services:
  app-crud-basico:
    container_name: app-crud-basico
    image: ${DOCKER_REGISTRY-}consoleappcrudbasico
    build:
      context: .
      dockerfile: console.app.crud.basico/Dockerfile

  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server
    environment:
      MSSQL_PID: "Developer"
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "DojoS665"
    ports:
      - "1522:1433"
    volumes:
      - ./docker/sql-server/dados/:/var/opt/mssql/data/

  sql-server-tools:
    image: mcr.microsoft.com/mssql-tools
    container_name: "sql-server-tools"
    depends_on:
      - sql-server
    volumes:
      - ./docker/sql-server/scripts/:/tmp/scripts-sql/
    command:
       /bin/bash -c '
         echo "Iniciando a execucaoo do script de criacao e carga de dados...";
         /tmp/scripts-sql/init-database.sh;
         sleep infinity;'